# SPDX-License-Identifier: MIT
using BenchmarkTools
using Base.Threads: @threads, @spawn
include("core/types.jl")
include("core/element.jl")
include("core/amino_acid.jl")
include("core/atom.jl")
include("core/pdb_atom.jl")
include("core/bond.jl")
include("core/chain.jl")
include("core/molecule.jl")
include("core/pdb_molecule.jl")
include("core/residue.jl")
include("core/fragment.jl")
include("core/nucleotide.jl")
include("core/protein.jl")

include("sasa/pdb.jl")
include("sasa/atomic_radius.jl")
include("sasa/hashbox.jl")
include("sasa/sasa.jl")
include("sasa/interface.jl")
include("sasa/interface5A.jl")
include("sasa/residue_residue_pair.jl")
include("sasa/count_interface_residues.jl")
include("sasa/count_residue_areas.jl")
include("sasa/count_interface_residue_pairs.jl")
include("sasa/gather_data.jl")